---
title: "segs_redo"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

## sample gfw_data to csv

Ran on [rstudio.ships4whales.org](http://rstudio.ships4whales.org) to produce 3 days worth of data from points `gfw_data`: `gfw_data_2020-04-02-to-04.csv`.

```{python, eval=F}
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account
import csv

#FILL IN YOUR PATH TO THE 'Benioff Ocean Initiative-454f666d1896.json'
credentials_json = '/home/admin/Benioff Ocean Initiative-454f666d1896.json'
credentials = service_account.Credentials.from_service_account_file(credentials_json)

project_id = 'benioff-ocean-initiative'
client = bigquery.Client(credentials= credentials,project=project_id)

sql = "SELECT MAX(timestamp) AS timestamp_max FROM clustered_datasets.gfw_data WHERE date(timestamp) > '2020-01-01';"
client.query(sql).to_dataframe()
# timestamp_max = 2020-04-04 23:59:58+00:00

# get 3 days of data (timestamp_max = 2020-04-04 23:59:58+00:00)
sql = """
  SELECT
    mmsi, timestamp, lon, lat, speed_knots, implied_speed_knots, source
  FROM
    `benioff-ocean-initiative.clustered_datasets.gfw_data`
  WHERE 
    DATE(timestamp) > '2020-04-01'
  """
df = client.query(sql).to_dataframe()
df.to_csv('/home/admin/plumber-api/gfw_data_2020-04-02-to-04.csv')
```

## get top3 ships

```{r}
library(tidyverse)
library(here)
library(sf)
library(units)
library(lubridate)
library(mapview)
library(leaflet)
library(DT)
here = here::here

d_csv    <- here("data/gfw_data_2020-04-02-to-04.csv")
top3_csv <- here("data/gfw_data_2020-04-02-to-04_top3.csv")
lns_geo  <- here("data/gfw_data_2020-04-02-to-04_top3_lns.geojson")
```


```{r}
d <- read_csv(d_csv) %>% 
  arrange(mmsi, timestamp)
d %>% head() %>% datatable()

d_n <- d %>% 
  group_by(mmsi) %>% 
  summarise(
    n = n(),
    implied_speed_knots_avg = mean(implied_speed_knots, na.rm=T)) %>% 
  ungroup() %>% 
  arrange(desc(n))
d_n %>% datatable()

top3 <- d_n %>% 
  slice(1:100) %>% 
  arrange(desc(implied_speed_knots_avg)) %>% 
  slice(1:3)

d %>% 
  filter(mmsi %in% top3$mmsi) %>% 
  write_csv(top3_csv)

top3 %>% datatable()
```


## calculate speed bins

```{r}
pts <- read_csv(top3_csv) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = F)
mapview(pts)

empty <- st_as_sfc("POINT(EMPTY)")
pts <- pts %>%
  arrange(mmsi, timestamp) %>% 
  mutate(
    date = date(timestamp)) %>% 
  group_by(mmsi, date) %>% # IMPORTANT!
  mutate(
    calc_time_s      = difftime(
      lead(timestamp), timestamp, units = "secs") 
      %>% as.numeric(),
    calc_dist_m      = st_distance(
      geometry, lead(geometry, default = empty), by_element = TRUE) 
      %>% set_units(m) %>% as.numeric(),
    speed_calc_knots = calc_dist_m / calc_time_s * 1.94384)

hist(pts$speed_calc_knots)

speed_bins = c(0, 10, 12, 15, Inf)
pts <- pts %>%
  mutate(
    speed_calc_bin = cut(speed_calc_knots, speed_bins))

ggplot(aes(x = speed_calc_bin), data = pts) +
  geom_bar()
```

## differentiate segments

```{r}
# identify rows ending a segment
pts <- pts %>%
  mutate(
    seg_chg = 
      (lead(speed_calc_bin) != speed_calc_bin) | 
      (timestamp == max(timestamp)))

# repeat rows to begin the next segment
pts <- rbind(
  pts %>% 
    ungroup(),
  pts %>% 
    ungroup() %>% 
    filter(
      seg_chg) %>% 
    mutate(
      seg_chg = F)) %>% 
  arrange(
    mmsi, timestamp, seg_chg) %>% 
  group_by(mmsi, date)

# create unique segment id
pts <- pts %>%
  mutate(
    seg_id  = cumsum(seg_chg))

pts %>%
  st_drop_geometry() %>%
  filter(
    mmsi == 303031000, 
    date ==	'2020-04-04', 
    seg_id %in% 24:26) %>%
  datatable()

```

## construct line segments

```{r}
lns <- pts %>%
  group_by(mmsi, date, seg_id) %>% 
  summarize(
    speed_calc_bin       = first(speed_calc_bin),
    timestamp_beg        = min(timestamp),
    timestamp_end        = max(timestamp),
    speed_calc_knots_avg = mean(speed_calc_knots, na.rm = T),
    geom = st_union(geometry) %>% 
      st_cast("LINESTRING"))
write_sf(lns, lns_geo, delete_dsn = T)

lns <- read_sf(lns_geo)

pal <- colorFactor("Spectral", lns$speed_calc_bin, ordered = T)

leaflet(lns) %>%
  addProviderTiles(
    providers$Esri.OceanBasemap,
    options = providerTileOptions(
      opacity = 0.5)) %>% 
  addPolylines(
      color = ~pal(speed_calc_bin),
      label = ~speed_calc_bin,
      opacity = 0.8) %>% 
  addLegend(
      pal = pal, values = ~speed_calc_bin, title = "Speed bin (knots)")
```


